### ISSUE TITLE
Doesn't spoof the value of navigator.userAgent

### ISSUE THREAD

**Issue by ghost** [LeoTindall/randomua#6]
Without also ensuring that the value of navigator.userAgent is set to the spoofed string, it will be trivial for any site capable of serving JavaScript (and having it executed) to infer and ignore the spoofed request header.

With the WWW becoming ever less useful without at least allowing 1st-party JS, this may compromise the effectiveness of this add-on when confronted with antagonists willing to post back data from client-side. It'd be nice to plug this last leak.

**Comment by NoraCodes** [comment]
Unfortunately the WebExtension API doesn't provide a way to do that, afaik

**Comment by ghost** [comment]
What about RegisteredContentScript? See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts/RegisteredContentScript

**Comment by guzszisvww** [comment]
@NoraCodes, but XUL-addon API provides a way to do that.
Could you please at least do this for the XUL-version of add-on? Many people continue to use old versions of Firefox.

Thank you very much.

**Comment by NoraCodes** [comment]
XUL extensions exist for this behavior. This is a WebExtension.

**Comment by 0xnullb** [comment]
A possible solution to spoofing `navigator.userAgent` is by injecting a script into the page before anything else loads (so that websites' UA detection don't run before spoofing) which then modifies the `navigator` object itself.

I'm not familiar with creating an extension for Firefox, otherwise I would have created a reproducible example, but I found some resources that could be helpful in doing this:

[This](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Modify_a_web_page) seems like a good place to start for injecting a script into a web page.

The injected script can modify the contents of the `navigator` object by using [Object.defineProperty(...)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty0).

An example usage of `Object.defineProperty(...)`:

```javascript
Object.defineProperty(navigator, 'userAgent', {
  value: 'Chrome',
  writable: false
});
```

Doing `navigator.userAgent` in the console yields `Chrome`.

Note that there are still other properties on the `navigator` object that store individual user agent information, such as `appCodeName` and `oscpu`, so these will need to be modified in addition to `navigator.userAgent`.

I hope this helps in coming up with a solution to the problem :)
